#!/bin/bash

# This script is used to scaffold a new VKS Package leveraging Helm and Carvel.
# It creates the top level folders and files for a new VKS Package.
# It also creates the sample files for the VKS Package.
# It also checks if the required Carvel binaries are present.
# It also provides the sample commands for reference.

display_usage() { 
	echo "This script must be run with three arguments." 
	echo -e "\nUsage: $0 name-of-package version-details[x.y.z] registry-info" 
  echo -e "\nExample: $0 headlamp 0.39.0 us-central1-docker.pkg.dev/navneet-410819/whoami6443-public/ \n"
} 

# if less than three arguments supplied, display usage 
	if [  $# -le 2 ] 
	then 
		display_usage
		exit 1
	fi

# Capture arguments
PACKAGE_NAME=$1
PACKAGE_VERSION=$2
REGISTRY=$3

# Validate registry parameter is not empty
if [ -z "$REGISTRY" ]
then
	echo "ERROR: Registry information must be provided."
	display_usage
	exit 1
fi 
 
# check whether user had supplied -h or --help . If yes display usage 
	if [[ ( $@ == "--help") ||  $@ == "-h" ]] 
	then 
		display_usage
		exit 0
	fi 

cd "$PACKAGE_NAME" || exit 1
pwd
yq '.spec.valuesSchema.openAPIv3.properties' < ./carvel-artifacts/packages/"$PACKAGE_NAME".vsphere.fling.vmware.com/package.yml > ./dummy.yml
if [ ! -f AddonConfigDefinition-template.yml ]; then
    echo "WARN: AddonConfigDefinition-template.yml file not found! Creating one.."

cat > AddonConfigDefinition-template.yml << EOF
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfigDefinition
metadata:
  name: $PACKAGE_NAME.vsphere.fling.vmware.com.$PACKAGE_VERSION
  namespace: vmware-system-vks-public
spec:
  templateOutputResources:
    - targetClusterOutput:
        apiVersion: v1
        kind: Secret
        name: '{{.Cluster.name}}-$PACKAGE_NAME-values'
        namespace: vmware-system-tkg
        referenceType: ValuesRef
      template: |-
        stringData:
          values.yaml: |
        {{ toYaml .Values | indent 4}}
  schema:
    openAPIV3Schema:
      type: object
      properties:
EOF
fi

cat > AddonInstall-template.yml << EOF
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-$PACKAGE_NAME
  namespace: NAMESPACE_PLACEHOLDER
spec:
  addonRef:
    name: $PACKAGE_NAME
    namespace: vmware-system-vks-public
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: CLUSTER_NAME_PLACEHOLDER
  crossNamespaceSelection: Blocked
  stopMatchingBehavior: Delete
EOF

cat > AddonConfig-template.yml << EOF
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
  name: CLUSTER_NAME_PLACEHOLDER-$PACKAGE_NAME
  namespace: NAMESPACE_PLACEHOLDER
spec:
  addonConfigDefinitionRef:
    name: $PACKAGE_NAME.vsphere.fling.vmware.com.$PACKAGE_VERSION
    namespace: vmware-system-vks-public
  clusterName: CLUSTER_NAME_PLACEHOLDER
  values:
EOF
yq eval -i '.spec.values = load("./upstream/values.yaml")' ./AddonConfig-template.yml

# Since not all Helm charts have a valid and complete values.schema.json file
# we need to treat the schema generated by the kctrl - package.spec.valuesSchema.openAPIv3.properties as a source of truth.
# We then need to clean it up to ensure it is a valid OpenAPIv3 schema that the K8s API server can accept.
# We perform a series of transformations to ensure the schema is valid.

# 1. Remove all "oneOf" constructs that have integer and string types and replace them with x-kubernetes-int-or-string
yq eval -i '(.. | select(has("oneOf") and ([.oneOf[].type] | contains(["integer"])) and ([.oneOf[].type] | contains(["string"])))) |= (del(.oneOf) | .x-kubernetes-int-or-string = true | .default = null)' ./dummy.yml
# 2. Remove all "type: array" constructs that have empty items and replace them with "type: object" items
yq eval -i '(.. | select(has("type")  and .type == "array" and (.items | length == 0))) |= .items = {"type": "object"}' ./dummy.yml

yq eval -i '.spec.schema.openAPIV3Schema.properties = load("dummy.yml")' ./AddonConfigDefinition-template.yml

ACD=$(gzip -c ./AddonConfigDefinition-template.yml | base64 -w 0)
export ACD
yq -i '.metadata.annotations."addons.kubernetes.vmware.com/addon-config-definition"= env(ACD)' carvel-artifacts/packages/"$PACKAGE_NAME".vsphere.fling.vmware.com/package.yml

cp ./carvel-artifacts/packages/"$PACKAGE_NAME".vsphere.fling.vmware.com/package.yml ../repo/packages/"$PACKAGE_NAME".vsphere.fling.vmware.com/"$PACKAGE_VERSION".yml
# rm ./dummy.yml

##################################################
##### Sample commands for reference
##################################################
echo "Validate the AddOnConfigDefinition has a valid schema by running within the Supervisor Context -"
echo "kubectl apply -f AddonConfigDefinition-template.yml --dry-run=server --validate=true"
echo
echo "To push the package to the Registry, run the following commands -"
echo "cd repo"
echo "kctrl package repository release"
echo 
echo "Update the addon.yaml with the imagebundle information"